- name: nginx-playbbok
  hosts: node
  become: yes
  tasks:
   - name: install nginx 
     ansible.builtin.package:
      name: nginx
      state: present
   - name: start the nginx server
     ansible.builtin.service:
      name: httpd
      state: started