- name: variables for playbook
  hosts: localhost
  var_files:
  - variables.yml
  tasks:
  - name: variables 
    ansible.builtin.debug:
     msg: "hi im learning {{course}}, trainer is {{trainer}}, duration is {{duration}}"