- name: playlevel for prmopt 
  hosts: localhost 
  vars_prompt:
   - name: USERNAME
     prompt: please  enter your  USERNAME
     private: false   #user can see what they are entering 


   - name: PASSWORD
     prompt: please  enter your PASSWORD 
     private: true   #user can't see what they are entering 
  tasks:
  - name: variables for prompt 
    ansible.builtin.debug:
     msg: "print the {{USERNAME}}, AND {{PASSWORD}}"