- name: playlevel for prmopt 
  hosts: localhost 
  vars_prompt:
   - name: USERNAME
     prompt: please  enter your  USERNAME

   - name: PASSWORD
     prompt: please  enter your PASSWORD 
  tasks:
  - name: variables for prompt 
    ansible.builtin.debug:
    msg: "print the {{USERNAME}}, AND {{PASSWORD}}"